name: Sonar Cloud Scan
on:
  push:
    branches:
      - master

jobs:
  SonarCloudTrigger:
    name: Sonar Cloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Run Sonar Cloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}} # Needed to get PR